name: actions_on_main_branch
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'

jobs:
  job1:
    name: check_admin
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN: JavierHerreroPorras
    steps:
      - name: st1
        if: ${{ github.actor != JavierHerreroPorras }}
        run: exit 1
      - name: st2
        if: ${{ github.actor == JavierHerreroPorras }}
        run: echo "ok"
