name: actions_on_main_branch
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'

jobs:
  job1:
    name: check_admin
    runs-on: ubuntu-latest
    env:
      AUTORIZADO: JavierHerreroPorras
    steps:
      - name: st1
        if: ${{ github.actor != env.AUTORIZADO }}
        run: exit 1
      - name: st2
        if: ${{ github.actor == env.AUTORIZADO }}
        run: echo "ok"
